#!/bin/bash

#SBATCH --output /home/ahmadkhana/Desktop/etiv-comparison/freesurfer8/log/slurm_output/%A_%a.out # saves output as (jobID)_out.out 
#SBATCH --error /home/ahmadkhana/Desktop/etiv-comparison/freesurfer8/log/slurm_output/%A_%a.err # saves error as (jobID)_err.out 
#SBATCH --ntasks=7
#SBATCH --cpus-per-task 10
#SBATCH --time=2-23:55:00
#SBATCH --mem=768000
#SBATCH --partition=HPC-CPUs

module load singularity

BASE="/home/ahmadkhana/Desktop/etiv-comparison/freesurfer8"
LIST="$BASE/log/subject_list.txt"
SUBJECTS_PER_JOB=7

# Read csv-file into array
mapfile -t input < $1

# get sid from csv
a=(${input[SLURM_ARRAY_TASK_ID]})

# settings
PROJECT_DIR=/groups/ag-reuter/projects/freesurfer-tests/test-cases/20250502
DATA_SUBDIR=data
OUTPUT_SUBDIR=output

# Display info
echo "Command file: $1"
echo "Job Id: $SLURM_JOB_ID"
echo "Task Id: $SLURM_ARRAY_TASK_ID of $SLURM_ARRAY_TASK_COUNT"
echo ${a[*]}

id=`echo ${a[0]} | sed "s/,.*//"`
flag_3t=`echo ${a[0]} | sed "s/.*,\(.*\),.*/\1/"`
flag_cm=`echo ${a[0]} | sed "s/.*,//"`

# source freesurfer
#export FREESURFER_HOME=/groups/ag-reuter/software-centos/fs80
#source /groups/ag-reuter/software-centos/fs80/SetUpFreeSurfer.sh

# Create cmd
#cmd="recon-all -i ${PROJECT_DIR}/${DATA_SUBDIR}/${id}/001.mgz -all -subjid ${id} -sd ${PROJECT_DIR}/${OUTPUT_SUBDIR} ${flag_3t} ${flag_cm}"
#cmd="singularity exec --no-mount home,cwd -e -B ${PROJECT_DIR}:/data ${PROJECT_DIR}/singularity/diersk_freesurfer_80.sif /opt/fs80/recon-all -i /data/${DATA_SUBDIR}/${id}/001.mgz -all -subjid ${id} -sd /data/${OUTPUT_SUBDIR} ${flag_3t} ${flag_cm}"

# Display cmd
#echo $cmd

# Create directory
#mkdir -p ${PROJECT_DIR}/${OUTPUT_SUBDIR}/${id}

# Run freesurfer from the input directory
#cd ${PROJECT_DIR}/${OUTPUT_SUBDIR}/${id}

# Display time
echo "Started at "`date`

# Run cmd
#echo $cmd > ${PROJECT_DIR}/${OUTPUT_SUBDIR}/${id}_fs8.log 2>&1

singularity exec --no-mount home,cwd -e -B ${PROJECT_DIR}:/data ${PROJECT_DIR}/singularity/diersk_freesurfer_80.sif /bin/bash -c "source /opt/fs80/SetUpFreeSurfer.sh && /opt/fs80/bin/recon-all -i /data/${DATA_SUBDIR}/${id}/001.mgz -parallel -openmp 8 -all -subjid ${id} -sd /data/${OUTPUT_SUBDIR} ${flag_3t} ${flag_cm}" > ${PROJECT_DIR}/${OUTPUT_SUBDIR}/${id}_fs8.log 2>&1

# Display time
echo "Finished at "`date`

# Recon all
# singularity exec --nv -e /home/ahmadkhana/Desktop/etiv-comparison/freesurfer/singularity/diersk_freesurfer_80.sif /bin/bash -c "source /opt/fs80/SetUpFreeSurfer.sh && /opt/fs80/bin/recon-all -i /home/ahmadkhana/Desktop/etiv-comparison/freesurfer/data/data_retest-oasis1/OAS1_0061_MR1/OAS1_0061_MR1.nii.gz -parallel -openmp 8 -all -subjid OAS1_0061_MR1 -sd /home/ahmadkhana/Desktop/etiv-comparison/freesurfer/results/ -3T -cm"


# segment_subregions thalamus --cross bert
# singularity exec --nv -e /home/ahmadkhana/Desktop/etiv-comparison/freesurfer/singularity/diersk_freesurfer_80.sif /bin/bash -c "source /opt/fs80/SetUpFreeSurfer.sh && segment_subregions thalamus --cross OAS1_0061_MR1"

# Fixed segment_subregions:
# singularity exec --nv -e \
# -B /home/ahmadkhana/Desktop/etiv-comparison/freesurfer/results:/mnt/results \
# /home/ahmadkhana/Desktop/etiv-comparison/freesurfer/singularity/diersk_freesurfer_80.sif \
# /bin/bash -c "source /opt/fs80/SetUpFreeSurfer.sh && \
# export SUBJECTS_DIR=/mnt/results && \
# segment_subregions thalamus --cross OAS1_0061_MR1"


# mri_sclimbic_seg
# singularity exec --nv -e /home/ahmadkhana/Desktop/etiv-comparison/freesurfer/singularity/diersk_freesurfer_80.sif /bin/bash -c "source /opt/fs80/SetUpFreeSurfer.sh && mri_sclimbic_seg --i /home/ahmadkhana/Desktop/etiv-comparison/freesurfer/data/data_retest-oasis1/OAS1_0061_MR1/OAS1_0061_MR1.nii.gz --o /home/ahmadkhana/Desktop/etiv-comparison/freesurfer/results/OAS1_0061_MR1.sclimbic.mgz"
# freeview /home/ahmadkhana/Desktop/etiv-comparison/freesurfer/data/data_retest-oasis1/OAS1_0061_MR1/OAS1_0061_MR1.nii.gz /home/ahmadkhana/Desktop/etiv-comparison/freesurfer/results/OAS1_0061_MR1.sclimbic.mgz:colormap=lut:lut=$FREESURFER_HOME/models/sclimbic.ctab